### ISSUE TITLE
Crash when running bounds algorithm

### ISSUE THREAD

**Issue by jpsember** [jpsember/java-geom#13]
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 34, Size: 13
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at geom.GeomApp.perform(GeomApp.java:332)
	at sample.BoundsOper.generate(BoundsOper.java:170)
	at sample.BoundsOper.processUserEvent(BoundsOper.java:98)
	at testbed.TestBed.userEventManagerListener(TestBed.java:65)
	at js.widget.SliderWidget.stateChanged(SliderWidget.java:54)
	at javax.swing.JSlider.fireStateChanged(JSlider.java:432)
	at javax.swing.JSlider$ModelListener.stateChanged(JSlider.java:350)
	at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
	at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
	at javax.swing.DefaultBoundedRangeModel.setValueIsAdjusting(DefaultBoundedRangeModel.java:231)
	at javax.swing.JSlider.setValueIsAdjusting(JSlider.java:652)
	at com.apple.laf.AquaSliderUI$TrackListener.mouseReleased(AquaSliderUI.java:337)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.RuntimeException: RuntimeException, findOperationForEditableObject selected elements disagrees with elements:
    {          "clipboard" : [  ],
      "duplication_offset" : [ 0,0 ],
                "elements" : [ {    "" : "pt",
                                 "loc" : [ 877,783 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 451,713 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 438,280 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 1132,143 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 630,504 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 1115,319 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 29,540 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 576,628 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 159,232 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 1182,677 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 1114,630 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 868,596 ]
                               },
                               {    "" : "pt",
                                 "loc" : [ 629,363 ]
                               } ],
       "selected_elements" : [ 34 ]
    };
 .. Tools.die:483
 .. DefaultOper.findOperationForEditableObject:262
 .. DefaultOper.doStartDrag:219
 .. DefaultOper.processUserEvent:86
 .. UserEventManager.processUserEvent:94
 .. EditorPanel.generateMouseEvent:245
 .. EditorPanel.mouseDragged:205
 .. Component.processMouseMotionEvent:6573
 .. JComponent.processMouseMotionEvent:3339
 .. Component.processEvent:6294
 .. Container.processEvent:2234
 .. Component.dispatchEventImpl:4881
 .. Container.dispatchEventImpl:2292
 .. Component.dispatchEvent:4703
 .. LightweightDispatcher.retargetMouseEvent:4898
```

**Comment by jpsember** [comment]
To reproduce, run the algorithm with a lot of points, and step into it adding about half of them.  Then decrease the number of points... it will crash as it maybe tries to step past the logical stopping point?

**Comment by jpsember** [comment]
No... something to do with attempting to edit an unmodifiable list...

**Comment by jpsember** [comment]
I think I need to revisit the wisdom of making data type arrays (and maps, etc) unmodifiable; but fix this issue first.

**Comment by jpsember** [comment]
The bug is because the controls might change the script, e.g., reduce the number of elements, and the selected elements list is not corrected to compensate.
